-- drop da
--
-- CREATE TABLE IF NOT EXISTS SOUND
-- (
--     id   BIGINT AUTO_INCREMENT PRIMARY KEY,
--     text VARCHAR(255),
--     url  VARCHAR(255)
-- );
--
--
-- INSERT INTO SOUND (text, url)
-- VALUES ('dog', 'https://cdn.freesound.org/previews/448/448723_4473224-lq.mp3');
-- INSERT INTO SOUND (text, url)
-- VALUES ('rain', 'https://cdn.freesound.org/previews/243/243629_3509815-lq.mp3');
--
